FROM ubuntu-base:20.04

ENV DEBIAN_FRONTEND=noninteractive TZ="Europe/London"

# bake
RUN mkdir -p /home/ns3dce/dce-linux-dev
WORKDIR /home/ns3dce/dce-linux-dev

RUN git clone https://gitlab.com/nsnam/bake.git

WORKDIR /home/ns3dce/dce-linux-dev/bake
# checkout the latest commit as of 2023/06/16
RUN git checkout 66702155d4e8f07e91af542830be04ee5803cddd

RUN export PATH=`pwd`/build/bin${PATH:+:$PATH}
RUN export PYTHONPATH=`pwd`/build/lib${PYTHONPATH:+:$PYTHONPATH}
RUN export LD_LIBRARY_PATH=`pwd`/source/ns-3-dce/build/lib:`pwd`/source/ns-3-dev/build/lib:`pwd`/build/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

RUN export CPATH=$CPATH:/home/ns3dce/dce-linux-dev/source/ns-3-dev/include

#COPY bakeconf.xml.patch .
#RUN git apply --whitespace=warn < bakeconf.xml.patch
WORKDIR /home/ns3dce/dce-linux-dev

RUN ./bake/bake.py configure -e dce-linux-dev && \
    ./bake/bake.py --debug download -vvv

#WORKDIR /home/ns3dce/dce-linux-dev/source/ns-3-dev
#COPY ns3.patch .
#RUN git apply < ns3.patch
#
#WORKDIR /home/ns3dce/dce-linux-dev
#
#RUN ./bake/bake.py build -vvv -j $(nproc)
#
