FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive TZ="Europe/London"

RUN apt-get update && apt-get install --no-install-recommends -y mercurial libexpat1-dev git-core build-essential bison \
    flex libssl-dev libdb-dev libpcap-dev libc6-dbg libsysfs-dev gawk indent \
    pkg-config autoconf automake sudo ccache libsaxonb-java openjdk-8-jre-headless python-setuptools \
    bc wget python3-pip software-properties-common apt-transport-https ca-certificates \
    libc6-i386 libc-bin libc6-dbg libc6-dev vim python3-dev python-dev \
    python3-gi-cairo gir1.2-gtk-3.0 python3-pygraphviz cmake vim htop

RUN useradd -ms /bin/bash ns3dce && adduser ns3dce sudo && echo -n 'ns3dce:ns3dce' | chpasswd

# Enable passwordless sudo for users under the "sudo" group
RUN sed -i.bkp -e \
      's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' \
      /etc/sudoers

USER ns3dce

WORKDIR /home/ns3dce/

RUN pip install --user distro requests cppyy

ENV PATH /usr/lib/ccache:${PATH}

