FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive TZ="Europe/London"

 
RUN apt-get update && apt-get install -y libc6 libc-bin libc6-dbg libc6-dev libc6-i386 libc6-dev-i386 
RUN apt-get update && apt-get install -y mercurial libexpat1-dev git-core build-essential bison \
    flex libssl-dev libdb-dev libpcap-dev libsysfs-dev gawk indent \
    pkg-config autoconf automake sudo ccache libsaxonb-java openjdk-8-jre-headless python-setuptools \
    bc wget python3-pip software-properties-common apt-transport-https ca-certificates rsync

RUN useradd -ms /bin/bash ns3dce && adduser ns3dce sudo && echo -n 'ns3dce:ns3dce' | chpasswd

# Enable passwordless sudo for users under the "sudo" group
RUN sed -i.bkp -e \
      's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' \
      /etc/sudoers

RUN pip install --upgrade pip setuptools-scm distro requests

USER ns3dce

WORKDIR /home/ns3dce/

ENV PATH /usr/lib/ccache:${PATH}

# bake
RUN mkdir -p /home/ns3dce/dce-linux-dev
WORKDIR /home/ns3dce/dce-linux-dev
COPY ns3-dce.patch .
RUN git clone https://gitlab.com/ParthPratim1/bake

WORKDIR /home/ns3dce/dce-linux-dev/bake
RUN git checkout 3e3414dc775d23a1f9b18b35cd720d8e90db10fc

RUN export PATH=`pwd`/build/bin${PATH:+:$PATH} && \
    export PYTHONPATH=`pwd`/build/lib${PYTHONPATH:+:$PYTHONPATH} && \
    export LD_LIBRARY_PATH=`pwd`/source/ns-3-dce/build/lib:`pwd`/source/ns-3-dev/build/lib:`pwd`/build/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH} && \
    export CPATH=$CPATH:/home/ns3dce/dce-linux-dev/source/ns-3-dev/include

COPY bakeconf.xml.patch .
#RUN git apply --whitespace=warn < bakeconf.xml.patch
RUN git apply --reject --whitespace=fix < bakeconf.xml.patch
WORKDIR /home/ns3dce/dce-linux-dev

RUN ./bake/bake.py configure -e dce-linux-dev && \
    ./bake/bake.py  --debug download -vvv

WORKDIR /home/ns3dce/dce-linux-dev/source/ns-3-dev
COPY ns3.patch .
RUN git apply < ns3.patch

WORKDIR /home/ns3dce/dce-linux-dev

RUN ./bake/bake.py download && \
    ./bake/bake.py build -vvv -j $(nproc)

